behaviors:
  Robot_Record:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 0.00025
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    # -----------------------------------------
    # âœ” OLD ML-Agents Behavioral Cloning syntax
    # -----------------------------------------
    behavioral_cloning:
      demo_path: Assets/ML-Agents/Demos/robot_demo.demo
      strength: 0.5
      steps: 200000
      batch_size: 512
      num_epochs: 3

    max_steps: 400000
    time_horizon: 128
    summary_freq: 10000
