behaviors:
  Robot_Record:
    trainer_type: ppo

    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.00015
      beta: 0.005
      epsilon: 0.15
      lambd: 0.92
      num_epoch: 4

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

    max_steps: 700000
    time_horizon: 256
    summary_freq: 8000

    keep_checkpoints: 10
    checkpoint_interval: 50000
